#!/usr/bin/env bash
# 03-keyvault.sh — export every secret from the legacy Key Vault(s), then
# encrypt the bundle with openssl AES-256-CBC and shred the plaintext.
#
# A 256-bit random passphrase is generated by the script. It is printed once
# at the end — save it in 1Password (or equivalent) immediately. Losing the
# passphrase = losing the only copy of legacy credentials.

source "$(dirname "$0")/lib.sh"
log_to "03-keyvault"

PLAINTEXT_DIR="$BACKUP_DIR/keyvault.tmp"
TARBALL="$BACKUP_DIR/keyvault.tar.gz"
ENCRYPTED="$BACKUP_DIR/keyvault.enc"
PASSPHRASE_FILE="$BACKUP_DIR/keyvault.passphrase.SAVE-THIS-THEN-DELETE.txt"

if [[ -f "$ENCRYPTED" ]]; then
  log "↷ $ENCRYPTED already exists. Delete it to re-run."
  exit 0
fi

mkdir -p "$PLAINTEXT_DIR"
chmod 700 "$PLAINTEXT_DIR"

step "3.1  Dump every secret from each vault"
SCHOOLOGY_FOUND=0
for kv in "$LEGACY_KV_OEA" "${LEGACY_KV_LMS:-}"; do
  [[ -z "$kv" ]] && continue
  if ! az keyvault show -n "$kv" --query name -o tsv >/dev/null 2>&1; then
    warn "Vault $kv not found — skipping"
    continue
  fi
  mkdir -p "$PLAINTEXT_DIR/$kv"
  log "▶ $kv"
  names="$(az keyvault secret list --vault-name "$kv" --query "[].name" -o tsv 2>/dev/null || true)"
  if [[ -z "$names" ]]; then
    warn "  (no secrets accessible — check RBAC / access policy)"
    continue
  fi
  while IFS= read -r s; do
    [[ -z "$s" ]] && continue
    if az keyvault secret show --vault-name "$kv" --name "$s" \
         --query "{name:name,value:value,tags:tags,contentType:contentType,attributes:{enabled:attributes.enabled,created:attributes.created,updated:attributes.updated}}" \
         -o json > "$PLAINTEXT_DIR/$kv/$s.json" 2>/dev/null; then
      echo "  · $s"
      case "$s" in
        schoology*) SCHOOLOGY_FOUND=$((SCHOOLOGY_FOUND + 1)) ;;
      esac
    else
      warn "  ✗ failed to read $s"
    fi
  done <<<"$names"
done
ok "Secrets exported to $PLAINTEXT_DIR (plaintext, will be encrypted next)"

step "3.2  Confirm Schoology keys present"
if [[ $SCHOOLOGY_FOUND -ge 2 ]]; then
  ok "Found $SCHOOLOGY_FOUND Schoology-prefixed secret(s) — good"
else
  warn "Only $SCHOOLOGY_FOUND Schoology secret(s) found. Verify before tearing down legacy."
fi

step "3.3  Tar + encrypt the bundle"
# 1) Tar+gzip the plaintext folder
tar c -C "$BACKUP_DIR" "$(basename "$PLAINTEXT_DIR")" | gzip > "$TARBALL"
log "  tarball: $(du -h "$TARBALL" | cut -f1)"

# 2) Generate a 256-bit random passphrase (43 chars base64)
PASS="$(openssl rand -base64 32)"

# 3) Encrypt the tarball with AES-256-CBC + PBKDF2 (high iter count)
PASSPHRASE_ENV="$PASS" openssl enc -aes-256-cbc -pbkdf2 -iter 600000 \
  -pass env:PASSPHRASE_ENV \
  -in "$TARBALL" \
  -out "$ENCRYPTED"
ok "Encrypted: $ENCRYPTED ($(du -h "$ENCRYPTED" | cut -f1))"

step "3.4  Verify the bundle decrypts"
DECRYPT_TEST="$BACKUP_DIR/.kv-decrypt-test"
PASSPHRASE_ENV="$PASS" openssl enc -d -aes-256-cbc -pbkdf2 -iter 600000 \
  -pass env:PASSPHRASE_ENV \
  -in "$ENCRYPTED" \
  -out "$DECRYPT_TEST" 2>/dev/null

if tar tzf "$DECRYPT_TEST" >/dev/null 2>&1; then
  ok "Decryption verified — tarball is intact"
  tar tzf "$DECRYPT_TEST" 2>/dev/null | head -10 | sed 's/^/    /'
else
  die "Decryption verify failed!"
fi
rm -f "$DECRYPT_TEST"

step "3.5  Write passphrase to a file (you'll move it to 1Password)"
cat > "$PASSPHRASE_FILE" <<EOF
$PASS

──────────────────────────────────────────────────────────
This passphrase decrypts: $ENCRYPTED

Save it in 1Password / Bitwarden / your password manager,
then DELETE this file:
  shred -u "$PASSPHRASE_FILE"

To decrypt later:
  openssl enc -d -aes-256-cbc -pbkdf2 -iter 600000 \\
    -pass pass:"<the passphrase>" \\
    -in keyvault.enc -out keyvault.tar.gz
  tar xzf keyvault.tar.gz
──────────────────────────────────────────────────────────
EOF
chmod 600 "$PASSPHRASE_FILE"
ok "Passphrase saved to $PASSPHRASE_FILE  (chmod 600)"

step "3.6  Shred the plaintext + tarball"
if have shred; then
  find "$PLAINTEXT_DIR" -type f -exec shred -u {} +
  shred -u "$TARBALL"
else
  find "$PLAINTEXT_DIR" -type f -exec sh -c 'dd if=/dev/urandom of="$1" bs=4k count=1 conv=notrunc status=none && rm -f "$1"' _ {} \;
  dd if=/dev/urandom of="$TARBALL" bs=4k count=1 conv=notrunc status=none && rm -f "$TARBALL"
fi
rm -rf "$PLAINTEXT_DIR"
ok "Plaintext shredded — only $ENCRYPTED remains"

echo
ok "KEY VAULT BACKUP COMPLETE"
echo
echo "  ┌────────────────────────────────────────────────────────────────┐"
echo "  │  ACTION REQUIRED:                                              │"
echo "  │  1. Open: $PASSPHRASE_FILE"
echo "  │  2. Copy the passphrase to 1Password (or equivalent)           │"
echo "  │  3. Run: shred -u \"$PASSPHRASE_FILE\""
echo "  │  4. The .enc file becomes useless without the passphrase.      │"
echo "  └────────────────────────────────────────────────────────────────┘"
