CREATE TABLE raw_submission_summary (
  raw_id              UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
  school_id           UUID NOT NULL REFERENCES schools(school_id),
  ingestion_run_id    UUID NOT NULL REFERENCES ingestion_runs(run_id),
  source_file_path    TEXT NOT NULL,
  source_file_hash    TEXT NOT NULL,
  unique_key          TEXT NOT NULL,
  ingested_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  schoology_id        TEXT,
  first_name          TEXT,
  last_name           TEXT,
  unique_id_csv       TEXT,
  job_title           TEXT,
  gradebook_grade     TEXT,
  submission_no       INTEGER,
  submission_score    NUMERIC(10,4),
  question_label      TEXT,
  question_score      NUMERIC(10,4),
  UNIQUE (school_id, source_file_hash, unique_key)
);
CREATE INDEX raw_submission_summary_school_hash_idx ON raw_submission_summary (school_id, source_file_hash);
CREATE INDEX raw_submission_summary_run_idx ON raw_submission_summary (ingestion_run_id);

CREATE TABLE raw_student_submission (
  raw_id                 UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
  school_id              UUID NOT NULL REFERENCES schools(school_id),
  ingestion_run_id       UUID NOT NULL REFERENCES ingestion_runs(run_id),
  source_file_path       TEXT NOT NULL,
  source_file_hash       TEXT NOT NULL,
  unique_key             TEXT NOT NULL,
  ingested_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_uid               TEXT,
  username               TEXT,
  last_name              TEXT,
  first_name             TEXT,
  user_role_id           TEXT,
  user_school_id         TEXT,
  user_school_name       TEXT,
  course_nid             TEXT,
  course_name            TEXT,
  course_code            TEXT,
  section_nid            TEXT,
  section_name           TEXT,
  section_code           TEXT,
  section_instructors    TEXT,
  item_type              TEXT,
  item_id                TEXT,
  item_name              TEXT,
  first_access           TIMESTAMPTZ,
  latest_attempt         TIMESTAMPTZ,
  total_time             INTERVAL,
  submission_grade       NUMERIC(10,4),
  submission             INTEGER,
  question_id            TEXT,
  associated_question_id TEXT,
  question_type          TEXT,
  question               TEXT,
  position_number        TEXT,
  sub_question           TEXT,
  answer_submission      TEXT,
  correct_answer         TEXT,
  points_received        NUMERIC(10,4),
  points_possible        NUMERIC(10,4),
  session                TEXT,
  assessment_type        TEXT,
  subject                TEXT,
  grade                  TEXT,
  section                TEXT,
  file_name              TEXT,
  UNIQUE (school_id, source_file_hash, unique_key)
);
CREATE INDEX raw_student_submission_school_hash_idx ON raw_student_submission (school_id, source_file_hash);
CREATE INDEX raw_student_submission_run_idx ON raw_student_submission (ingestion_run_id);
CREATE INDEX raw_student_submission_school_item_idx ON raw_student_submission (school_id, item_id);
CREATE INDEX raw_student_submission_school_user_idx ON raw_student_submission (school_id, user_uid);

CREATE TABLE raw_question_data (
  raw_id                  UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
  school_id               UUID NOT NULL REFERENCES schools(school_id),
  ingestion_run_id        UUID NOT NULL REFERENCES ingestion_runs(run_id),
  source_file_path        TEXT NOT NULL,
  source_file_hash        TEXT NOT NULL,
  unique_key              TEXT NOT NULL,
  ingested_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  item_id                 TEXT,
  item_name               TEXT,
  question_id             TEXT,
  associated_question_id  TEXT,
  total_points            NUMERIC(10,4),
  question_type           TEXT,
  question                TEXT,
  position_number         TEXT,
  sub_question            TEXT,
  answer_option           TEXT,
  answer_breakdown_count  INTEGER,
  answer_breakdown_pct    NUMERIC(10,4),
  correct_answer          TEXT,
  correctly_answered      NUMERIC(10,4),
  most_points_earned      NUMERIC(10,4),
  least_points_earned     NUMERIC(10,4),
  average_points_earned   NUMERIC(10,4),
  standards_val           TEXT,
  session                 TEXT,
  assessment_type         TEXT,
  subject                 TEXT,
  grade                   TEXT,
  section                 TEXT,
  file_name               TEXT,
  question_no             TEXT,
  UNIQUE (school_id, source_file_hash, unique_key)
);
CREATE INDEX raw_question_data_school_hash_idx ON raw_question_data (school_id, source_file_hash);
CREATE INDEX raw_question_data_run_idx ON raw_question_data (ingestion_run_id);
CREATE INDEX raw_question_data_school_item_idx ON raw_question_data (school_id, item_id);
CREATE INDEX raw_question_data_school_question_idx ON raw_question_data (school_id, question_id);

CREATE TABLE raw_user (
  raw_id                   UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
  school_id                UUID NOT NULL REFERENCES schools(school_id),
  user_sync_run_id         UUID NOT NULL REFERENCES user_sync_runs(run_id),
  ingested_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  uid                      TEXT,
  id                       TEXT,
  school_uid               TEXT,
  name_title               TEXT,
  name_first               TEXT,
  name_first_preferred     TEXT,
  use_preferred_first_name BOOLEAN,
  name_middle              TEXT,
  name_middle_show         BOOLEAN,
  name_last                TEXT,
  name_display             TEXT,
  primary_email            TEXT,
  picture_url              TEXT,
  gender                   TEXT,
  position                 TEXT,
  grad_year                TEXT,
  username                 TEXT,
  password_hash            TEXT,
  role_id                  TEXT,
  tz_offset                TEXT,
  tz_name                  TEXT,
  language                 TEXT,
  child_uids               TEXT[],
  is_active                BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (school_id, uid)
);
CREATE INDEX raw_user_school_idx ON raw_user (school_id);
CREATE INDEX raw_user_run_idx ON raw_user (user_sync_run_id);
CREATE INDEX raw_user_school_role_idx ON raw_user (school_id, role_id);
